name: dl_lai
channels:
  - defaults
  - nvidia
  - pytorch
dependencies:
  - python=3.7.10
  - cpuonly
  - pytorch=1.8.1
  - jupyter
  - torchvision=0.9.1
  - pandas=1.1.5
  - matplotlib
  - scikit-learn
  - pip
  - pip:
    - tqdm==4.41
    - tabulate==0.8.9